import { Template, Match } from 'aws-cdk-lib/assertions';
import { App, Stack } from 'aws-cdk-lib';
import { Vpc } from 'aws-cdk-lib/aws-ec2';
import { Table, AttributeType } from 'aws-cdk-lib/aws-dynamodb';
import { Function, Runtime, Code } from 'aws-cdk-lib/aws-lambda';
import { Key } from 'aws-cdk-lib/aws-kms';
import { UserPool } from 'aws-cdk-lib/aws-cognito';
import { describe, it, expect } from 'vitest';
import { AdminConsoleStack } from '../lib/stacks/admin-console-stack.js';
import { resolve } from 'node:path';

describe('AdminConsoleStack', () => {
  it('creates Lambda + Function URL + CloudFront + WAF', () => {
    const app = new App();

    // Build a parent stack with the dependencies the admin stack needs
    const parent = new Stack(app, 'Parent', {
      env: { account: '111111111111', region: 'us-east-1' }
    });

    const vpc = new Vpc(parent, 'Vpc');
    const configTable = new Table(parent, 'ConfigTable', {
      partitionKey: { name: 'providerId', type: AttributeType.STRING }
    });
    const router = new Function(parent, 'Router', {
      runtime: Runtime.NODEJS_20_X,
      handler: 'index.handler',
      code: Code.fromInline('exports.handler=()=>{};')
    });
    const key = new Key(parent, 'Key');
    const pool = new UserPool(parent, 'Pool', { userPoolName: 'test' });

    // Use test fixture path
    const fixtureAssetPath = resolve(__dirname, './fixtures/admin-asset');

    const s = new AdminConsoleStack(app, 'AdminConsole', {
      env: { account: '111111111111', region: 'us-east-1' },
      vpc,
      configTable,
      searchRouterFn: router,
      secretsKmsKey: key,
      userPool: pool,
      userPoolId: 'us-east-1_TESTPOOL',
      userPoolClientId: 'testclient',
      hostedUiBaseUrl: 'https://test-pool.auth.us-east-1.amazoncognito.com',
      adminAssetPath: fixtureAssetPath
    });

    const t = Template.fromStack(s);

    // Verify the admin console Lambda exists. There is also a CDK-managed framework Lambda
    // generated by AwsCustomResource (used to patch the OAuth client callback URLs after the
    // CloudFront distribution exists, breaking the Lambda↔Distribution cycle).
    t.hasResourceProperties('AWS::Lambda::Function', {
      Runtime: 'nodejs20.x',
      MemorySize: 1024,
      Timeout: 15
    });

    // Verify Function URL exists
    t.hasResourceProperties('AWS::Lambda::Url', {
      AuthType: 'AWS_IAM'
    });

    // Verify CloudFront distribution exists
    t.resourceCountIs('AWS::CloudFront::Distribution', 1);

    // Verify WAF WebACL exists
    t.resourceCountIs('AWS::WAFv2::WebACL', 1);
    t.hasResourceProperties('AWS::WAFv2::WebACL', {
      Scope: 'CLOUDFRONT',
      DefaultAction: { Allow: {} }
    });

    // Verify outputs exist
    t.hasOutput('AdminDistDomainName', {});
    t.hasOutput('AdminFunctionUrl', {});
    t.hasOutput('AdminConsoleOAuthClientId', {});

    // Verify the Cognito Hosted UI OAuth client is wired correctly
    t.hasResourceProperties('AWS::Cognito::UserPoolClient', {
      ClientName: 'admin-console',
      AllowedOAuthFlows: ['code'],
      AllowedOAuthFlowsUserPoolClient: true,
      AllowedOAuthScopes: ['openid', 'email', 'profile'],
      SupportedIdentityProviders: ['COGNITO']
    });

    // Verify Lambda env exposes Hosted UI vars (consoleBaseUrl is derived from request URL at
    // runtime to avoid a Lambda → distribution → fnUrl → Lambda cycle).
    t.hasResourceProperties('AWS::Lambda::Function', {
      Environment: {
        Variables: Match.objectLike({
          COGNITO_HOSTED_UI_BASE_URL: 'https://test-pool.auth.us-east-1.amazoncognito.com'
        })
      }
    });
  });
});
